[package]
name = "spin-factors"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
serde = "1.0"
spin-app = { path = "../app" }
spin-factors-derive = { path = "../factors-derive" }
thiserror = "1.0"
tracing = { workspace = true }
wasmtime = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
spin-factors-derive = { path = "../factors-derive", features = ["expander"] }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }

[lints]
workspace = true
