[package]
name = "spin-factor-wasi"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
cap-primitives = "3.0.0"
spin-factors = { path = "../factors" }
wasmtime-wasi = { workspace = true }

[lints]
workspace = true
